# Generated by Django 4.0.5 on 2022-06-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_parts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parts',
            options={'verbose_name_plural': 'Parts'},
        ),
        migrations.AlterField(
            model_name='parts',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
